apiV1\authorization\Group_:
  type: entity
  table: groups
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 32
      unique: true
    description:
      type: text
      nullable: true
  oneToMany:
    users:
      targetEntity: GroupsUsers
      mappedBy: group_id
#  manyToMany:
#    users:
#      targetEntity: User
#      # The following is not required
#      joinTable:
#        name: groups_users
#        joinColumns:
#          group_id:
#            referencedColumnName: id
#        inverseJoinColumns:
#          user_id:
#            referencedColumnName: id

# http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html
# When we don’t explicitly specify a column name via the name option,
# Doctrine assumes the field name is also the column name.