# Doctrine Configuration
# TODO : [Q] How do you use this file as a config source?
doctrine:
  dbal:
    charset: utf8mb4
      default_table_options:
        charset: utf8mb4
        collate: utf8mb4_unicode_ci